# Generated by Django 6.0.6 on 2026-06-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.CharField(blank=True, max_length=100)),
                ('wb_a_pos', models.IntegerField(default=0)),
                ('wb_a_neg', models.IntegerField(default=0)),
                ('wb_b_pos', models.IntegerField(default=0)),
                ('wb_b_neg', models.IntegerField(default=0)),
                ('wb_ab_pos', models.IntegerField(default=0)),
                ('wb_ab_neg', models.IntegerField(default=0)),
                ('wb_o_pos', models.IntegerField(default=0)),
                ('wb_o_neg', models.IntegerField(default=0)),
                ('prbc_a_pos', models.IntegerField(default=0)),
                ('prbc_a_neg', models.IntegerField(default=0)),
                ('prbc_b_pos', models.IntegerField(default=0)),
                ('prbc_b_neg', models.IntegerField(default=0)),
                ('prbc_ab_pos', models.IntegerField(default=0)),
                ('prbc_ab_neg', models.IntegerField(default=0)),
                ('prbc_o_pos', models.IntegerField(default=0)),
                ('prbc_o_neg', models.IntegerField(default=0)),
                ('total_units', models.IntegerField(default=0)),
                ('bombay_pos', models.IntegerField(default=0)),
                ('bombay_neg', models.IntegerField(default=0)),
                ('sd_platelets', models.IntegerField(default=0)),
                ('sd_plasma', models.IntegerField(default=0)),
                ('ffp', models.IntegerField(default=0)),
                ('cryo_pp', models.IntegerField(default=0)),
                ('liquid_plasma', models.IntegerField(default=0)),
                ('rdp', models.IntegerField(default=0)),
                ('cryo_pre', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=10)),
                ('units', models.IntegerField(default=1)),
                ('hospital', models.CharField(max_length=255)),
                ('hospital_address', models.CharField(blank=True, max_length=255)),
                ('attendant_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('urgency', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('matched_donors_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('slots', models.IntegerField(default=100)),
                ('slots_booked', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='upcoming', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('recipients', models.IntegerField(default=0)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=10)),
                ('zone', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('last_donation', models.DateField(blank=True, null=True)),
                ('total_donations', models.IntegerField(default=0)),
                ('eligible', models.BooleanField(default=True)),
                ('next_eligible', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
