# Generated by Django 6.0.6 on 2026-06-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bloodrequest_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
